version: '3.7'

services:
  postgres:
    image: postgres:latest
    container_name: ${POSTGRES_HOST}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - ${POSTGRES_PORT}:${POSTGRES_PORT}
    env_file: ./.env
    environment:
      - POSTGRES_HOST=${POSTGRES_HOST}
      - POSTGRES_PORT=${POSTGRES_PORT}

  backend:
    container_name: backend
    build:
      context: ./backend
      dockerfile: ./Dockerfile.backend
    volumes:
      - ./backend/app:/app
    ports:
      - 8000:8000
    env_file: ./backend/.env
    restart: always
    tty: true
    depends_on:
      - postgres

  frontend:
    container_name: frontend
    build:
      context: ./frontend
      dockerfile: ./Dockerfile.frontend
    command: [ "npm", "start" ]
    volumes:
      - ./:/usr/src/app
    ports:
      - 3000:3000
    env_file: ./frontend/.env
    tty: true

volumes:
  postgres_data:
